### ISSUE TITLE
Build with babel

### ISSUE THREAD

**Issue by MatthieuLemoine** [IonicaBizau/scrape-it#24]
As `scrape-it` is written in ES6 it can't be used with Node < v4. 
A lot of people still use Node 0.10 or 0.12. 

It could be nice to build the project using babel.

**Comment by IonicaBizau** [comment]
People should upgrade to latest versions since the old ones contain security bugs.

On the other side, I have this on my list. Using [`dist-it`](https://github.com/IonicaBizau/dist-it/issues/7) I will set up a `prepublish` script to babelify the code.

Something similar is needed in another context, so, that's a thing. 👍

**Comment by MatthieuLemoine** [comment]
> People should upgrade to latest versions since the old ones contain security bugs.

You're absolutely right but not all end users are familiar with Node and some won't install a version which is not shipped by their distro (Ubuntu 14.04LTS for example shipping an old Node 0.10).

**Comment by IonicaBizau** [comment]
@MatthieuLemoine I recently published [`babel-it`](https://github.com/IonicaBizau/babel-it) which babelifies the code before `npm publish`.

I'm going to update all my npm packages with transpiled code. :rocket:

**Comment by IonicaBizau** [comment]
Fixed via #26. Wow, just look at my today's contributions, lol. :grin: :rocket:
