### ISSUE TITLE
Add a Dockerfile to build a container

### ISSUE THREAD

**Issue by shouze** [IonicaBizau/scrape-it#5]
This will help to distribute scrape-it as a service.

**Comment by IonicaBizau** [comment]
Thanks, @shouze! If that's helpful, let's do it. Contributions are welcome!

I didn't work with Docker, but I'm open to accept any changes that make this tool better. :sparkles:

**Comment by brunocascio** [comment]
Hi @IonicaBizau, please creates a new repository for the `Dockerfile`, (like scrape-it-docker). I'll fork it and contribute with this :)

**Comment by IonicaBizau** [comment]
@brunocascio Is there any specific reason why we should create a different project for the Docker thingy?

**Comment by brunocascio** [comment]
@IonicaBizau Because i'll use npm package for create the image, and don't need anything of the source repo. Would be possible use this repo, but think is a wrong place. Anything, let me know :)

**Comment by IonicaBizau** [comment]
@brunocascio I have no idea how Docker works at all. Maybe can you tell me more about workflow?

**Comment by brunocascio** [comment]
Basically Docker is an environment for virtualization using containers (LXC, linux kernel feature) and other linux/unix features like cgroups, UnionFS, etc with all beneficies that provides. (isolation, security, resources management, etc).

Each container is a linux process, sharing the kernel (and other linux libs) with all containers and Linux Host. It is the difference with the conventional VMM (like VBox or VMWare) that uses and runs a complete SO over an hypervisor.

Here in this project the approach is the portability, because you only need to install docker in host. All dependencies (nodejs, npm and node_modules) are builded in the Docker Image. Then, when you need to scrap a site just run a docker container from these image and it's all.

Sorry for my english :P

NOTE: This is only a very short introduction to Docker and how to benefit us!

For complete Docs, [here](https://www.docker.com/what-docker).

**Comment by IonicaBizau** [comment]
@brunocascio Thanks! And what is the difference of having the `Dockerfile` in this repository or in another one?

I'm still not sure how creating a new project helps. Is it just the download size, since you're saying the code will come from npm?

Thanks! 😁

**Comment by brunocascio** [comment]
Add a `Dockerfile` in this repo would be ok. But this file will have not nothing to do here. 
Also, If somebody want to use Dockerfile should clone the repo with ALL files instead of only the Dockerfile. 

It's only my opinion :) 

Otherwise, please let me know and i'll make a pull-request here 💃

**Comment by IonicaBizau** [comment]
@brunocascio Ah, I see! Is it because Docker takes the packages from git?

The repo itself is pretty tiny anyways. I'm also for splitting if that will be faster. 😁

**Comment by brunocascio** [comment]
Docker will take packages from npm instead of git.

So, I'll make a pull-request here later :)

**Comment by IonicaBizau** [comment]
Ah, great! Then I guess it's fine to add it here. Maybe later if anyone will complain about it we can split it. 😄 

Thanks!

**Comment by brunocascio** [comment]
@IonicaBizau Great! :)

**Comment by IonicaBizau** [comment]
Fixed via #31. 🎉
