### ISSUE TITLE
How to scrape ajax pages

### ISSUE THREAD

**Issue by kingcc** [IonicaBizau/scrape-it#59]
Hi,
  Some pages use ajax to get real contents, so scrape-it only scrape a blank page...

**Comment by kingcc** [comment]
Can you join a param about setTimeout or not ?

**Comment by CleristonBernardes** [comment]
I am having the same issue.

**Comment by IonicaBizau** [comment]
I will come up with a solution about this. Lots of people were mentioning it. For now, see this comment: https://github.com/IonicaBizau/scrape-it/issues/17#issuecomment-216533538

**Comment by roccomuso** [comment]
PhantomJS would be also useful to follow JS redirects etc.
Could you post an example of how to use scrape-it with Phantom?
thanks!

**Comment by LeonLiber** [comment]
I have written a full article about how to scrape AJAX (and such) pages.
[Check it out on Medium](https://medium.com/@ariklevliber/real-world-website-scraping-and-cvs-exporting-using-the-new-headless-chromium-cea3e5611388)

I used the new Chromium Headless because PhantomJS is, unfortunately, going away..

**Comment by IonicaBizau** [comment]
@LeonLiber Amazing article! :+1:

**Comment by edorivai** [comment]
Also, remember that when websites fetch over AJAX, it's very often easier to directly request from they API. It will often respond with structured JSON documents, which make your life a whole lot easier.
